// This file is auto-generated by TanStack Router.
// Regenerate with: `tsr generate` or `vinxi dev`
// Manual edits will be overwritten.
import { Route as rootRoute } from './routes/__root.js'
import { Route as IndexRoute } from './routes/index.js'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
  }
}

export const routeTree = rootRoute.addChildren([IndexRoute])