/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ElectricityRouteImport } from './routes/electricity'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminStorageRouteImport } from './routes/admin/storage'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ElectricityIndexRouteImport } from './routes/electricity/index'
import { Route as ElectricityOrderRouteImport } from './routes/electricity/order'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterVerifyRouteImport } from './routes/register/verify'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as OnboardingIndividualProfileIdRouteImport } from './routes/onboarding/individual/$profileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricityRoute = ElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ElectricityIndexRoute = ElectricityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElectricityRoute,
} as any)
const ElectricityOrderRoute = ElectricityOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ElectricityRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterVerifyRoute = RegisterVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => RegisterRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndividualProfileIdRoute =
  OnboardingIndividualProfileIdRouteImport.update({
    id: '/individual/$profileId',
    path: '/individual/$profileId',
    getParentRoute: () => OnboardingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/charts': typeof ChartsRoute
  '/documents': typeof DocumentsRoute
  '/electricity': typeof ElectricityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/savings': typeof SavingsRoute
  '/support': typeof SupportRoute
  '/videos': typeof VideosRoute
  '/wallet': typeof WalletRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/electricity/order': typeof ElectricityOrderRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/electricity/': typeof ElectricityIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/onboarding/individual/$profileId': typeof OnboardingIndividualProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/charts': typeof ChartsRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/savings': typeof SavingsRoute
  '/support': typeof SupportRoute
  '/videos': typeof VideosRoute
  '/wallet': typeof WalletRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/electricity/order': typeof ElectricityOrderRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin': typeof AdminIndexRoute
  '/electricity': typeof ElectricityIndexRoute
  '/register': typeof RegisterIndexRoute
  '/onboarding/individual/$profileId': typeof OnboardingIndividualProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/charts': typeof ChartsRoute
  '/documents': typeof DocumentsRoute
  '/electricity': typeof ElectricityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/savings': typeof SavingsRoute
  '/support': typeof SupportRoute
  '/videos': typeof VideosRoute
  '/wallet': typeof WalletRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/electricity/order': typeof ElectricityOrderRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/electricity/': typeof ElectricityIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/onboarding/individual/$profileId': typeof OnboardingIndividualProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/charts'
    | '/documents'
    | '/electricity'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/savings'
    | '/support'
    | '/videos'
    | '/wallet'
    | '/admin/storage'
    | '/admin/users'
    | '/electricity/order'
    | '/register/verify'
    | '/settings/security'
    | '/admin/'
    | '/electricity/'
    | '/register/'
    | '/onboarding/individual/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/charts'
    | '/documents'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/savings'
    | '/support'
    | '/videos'
    | '/wallet'
    | '/admin/storage'
    | '/admin/users'
    | '/electricity/order'
    | '/register/verify'
    | '/settings/security'
    | '/admin'
    | '/electricity'
    | '/register'
    | '/onboarding/individual/$profileId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/charts'
    | '/documents'
    | '/electricity'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/savings'
    | '/support'
    | '/videos'
    | '/wallet'
    | '/admin/storage'
    | '/admin/users'
    | '/electricity/order'
    | '/register/verify'
    | '/settings/security'
    | '/admin/'
    | '/electricity/'
    | '/register/'
    | '/onboarding/individual/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  ChartsRoute: typeof ChartsRoute
  DocumentsRoute: typeof DocumentsRoute
  ElectricityRoute: typeof ElectricityRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
  SavingsRoute: typeof SavingsRoute
  SupportRoute: typeof SupportRoute
  VideosRoute: typeof VideosRoute
  WalletRoute: typeof WalletRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electricity': {
      id: '/electricity'
      path: '/electricity'
      fullPath: '/electricity'
      preLoaderRoute: typeof ElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/electricity/': {
      id: '/electricity/'
      path: '/'
      fullPath: '/electricity/'
      preLoaderRoute: typeof ElectricityIndexRouteImport
      parentRoute: typeof ElectricityRoute
    }
    '/electricity/order': {
      id: '/electricity/order'
      path: '/order'
      fullPath: '/electricity/order'
      preLoaderRoute: typeof ElectricityOrderRouteImport
      parentRoute: typeof ElectricityRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/verify': {
      id: '/register/verify'
      path: '/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof RegisterVerifyRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/individual/$profileId': {
      id: '/onboarding/individual/$profileId'
      path: '/individual/$profileId'
      fullPath: '/onboarding/individual/$profileId'
      preLoaderRoute: typeof OnboardingIndividualProfileIdRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface AdminRouteChildren {
  AdminStorageRoute: typeof AdminStorageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStorageRoute: AdminStorageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ElectricityRouteChildren {
  ElectricityOrderRoute: typeof ElectricityOrderRoute
  ElectricityIndexRoute: typeof ElectricityIndexRoute
}

const ElectricityRouteChildren: ElectricityRouteChildren = {
  ElectricityOrderRoute: ElectricityOrderRoute,
  ElectricityIndexRoute: ElectricityIndexRoute,
}

const ElectricityRouteWithChildren = ElectricityRoute._addFileChildren(
  ElectricityRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingIndividualProfileIdRoute: typeof OnboardingIndividualProfileIdRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingIndividualProfileIdRoute: OnboardingIndividualProfileIdRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface RegisterRouteChildren {
  RegisterVerifyRoute: typeof RegisterVerifyRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterVerifyRoute: RegisterVerifyRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  ChartsRoute: ChartsRoute,
  DocumentsRoute: DocumentsRoute,
  ElectricityRoute: ElectricityRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
  SavingsRoute: SavingsRoute,
  SupportRoute: SupportRoute,
  VideosRoute: VideosRoute,
  WalletRoute: WalletRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
