-- Migration 0019: Create invoice_state enum (T-04.1.01.02)
--
-- Converts the invoices.state column from TEXT (with inline CHECK constraint)
-- to a proper PostgreSQL enum type. All 9 states are defined:
--   Draft, Unpaid, PaymentUnderReview, PartiallyFunded, Paid,
--   Overdue, Cancelled, PartiallyRefunded, Refunded
--
-- Rollback:
--   ALTER TABLE invoices ALTER COLUMN state TYPE TEXT;
--   ALTER TABLE invoices ADD CONSTRAINT ck_invoice_state
--     CHECK (state IN (
--       'Draft', 'Unpaid', 'PaymentUnderReview', 'PartiallyFunded',
--       'Paid', 'Overdue', 'Cancelled', 'PartiallyRefunded', 'Refunded'
--     ));
--   DROP TYPE IF EXISTS invoice_state;

-- ---------------------------------------------------------------------------
-- Create invoice_state enum type
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE invoice_state AS ENUM (
    'Draft',
    'Unpaid',
    'PaymentUnderReview',
    'PartiallyFunded',
    'Paid',
    'Overdue',
    'Cancelled',
    'PartiallyRefunded',
    'Refunded'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- Alter invoices.state column from TEXT to invoice_state enum
-- ---------------------------------------------------------------------------
ALTER TABLE invoices
  ALTER COLUMN state TYPE invoice_state
  USING state::invoice_state;

-- Drop the old CHECK constraint if it was named (Drizzle generates it as
-- a table-level constraint when using text('state', {enum: [...]})).
-- The constraint name is auto-generated by Drizzle, so we use a DO block
-- to drop it safely if it exists.
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname LIKE '%invoices%state%'
      AND contype = 'c'
  ) THEN
    EXECUTE (
      SELECT format('ALTER TABLE invoices DROP CONSTRAINT %I', conname)
      FROM pg_constraint
      WHERE conname LIKE '%invoices%state%'
        AND contype = 'c'
      LIMIT 1
    );
  END IF;
END $$;