const en = {
  invalidHistory: 'Invalid TOS history response.',
  historyFailed: 'Failed to load TOS versions',
  retry: 'Retry',
  preserveSource:
    'This document contains tables, images or HTML. Edit its original text here to preserve that content.',
  bold: 'Bold',
  italic: 'Italic',
  heading: 'Heading',
  bullets: 'Bullet list',
  numbers: 'Numbered list',
  quote: 'Quote',
  undo: 'Undo',
  redo: 'Redo',
  formatting: 'Formatting',
  persian: 'Persian content',
  english: 'English content',
  editorLoading: 'Loading editor...',
  requiredContent: 'Enter both Persian and English content.',
};
const fa: Record<keyof typeof en, string> = {
  invalidHistory: 'پاسخ تاریخچه شرایط معتبر نیست.',
  historyFailed: 'بارگذاری تاریخچه شرایط انجام نشد.',
  retry: 'تلاش دوباره',
  preserveSource:
    'این سند شامل جدول، تصویر یا HTML است. برای حفظ محتوا، متن اصلی را اینجا ویرایش کنید.',
  bold: 'پررنگ',
  italic: 'مورب',
  heading: 'عنوان',
  bullets: 'فهرست نشانه‌دار',
  numbers: 'فهرست شماره‌دار',
  quote: 'نقل قول',
  undo: 'واگرد',
  redo: 'از نو',
  formatting: 'قالب‌بندی',
  persian: 'محتوای فارسی',
  english: 'محتوای انگلیسی',
  editorLoading: 'در حال بارگذاری ویرایشگر...',
  requiredContent: 'محتوای فارسی و انگلیسی را وارد کنید.',
};
export const adminTosText = (locale: 'fa' | 'en') => (locale === 'fa' ? fa : en);
