const en = {
  invalidHistory: 'Invalid TOS history response.',
  historyFailed: 'Failed to load TOS versions',
  retry: 'Retry',
  draftChanged:
    'Another editor changed this draft. Your text is preserved. Reload the saved draft before continuing.',
  reloadDraft: 'Reload saved draft',
  unconfirmedWrite: 'The saved result could not be confirmed. Reload history before continuing.',
  currentVersion: 'Current published version',
  proposedVersion: 'Draft preview',
  noCurrent: 'No published version yet.',
  textChanges: 'Show text changes',
  changeLegend: 'Underlined text is added. Struck-through text is removed.',
  largeComparison: 'Too many changes to highlight. Review both documents above.',
  previewLoading: 'Loading preview...',
  materialChange: 'Mark as material change',
  previewChanged:
    'This draft changed after preview. Close this preview and reload before publishing.',
  previewRequired: 'Reload the draft to obtain a current publication preview.',
  preserveSource:
    'This document contains tables, images or HTML. Edit its original text here to preserve that content.',
  bold: 'Bold',
  italic: 'Italic',
  heading: 'Heading',
  bullets: 'Bullet list',
  numbers: 'Numbered list',
  quote: 'Quote',
  undo: 'Undo',
  redo: 'Redo',
  formatting: 'Formatting',
  persian: 'Persian content',
  english: 'English content',
  editorLoading: 'Loading editor...',
  requiredContent: 'Enter both Persian and English content.',
};
const fa: Record<keyof typeof en, string> = {
  invalidHistory: 'پاسخ تاریخچه شرایط معتبر نیست.',
  historyFailed: 'بارگذاری تاریخچه شرایط انجام نشد.',
  retry: 'تلاش دوباره',
  draftChanged:
    'ویرایشگر دیگری این پیش‌نویس را تغییر داده است. متن شما حفظ شده است. برای ادامه، پیش‌نویس ذخیره‌شده را دوباره بارگذاری کنید.',
  reloadDraft: 'بارگذاری پیش‌نویس ذخیره‌شده',
  unconfirmedWrite: 'نتیجه ذخیره تأیید نشد. پیش از ادامه، تاریخچه را دوباره بارگذاری کنید.',
  currentVersion: 'نسخه منتشرشده فعلی',
  proposedVersion: 'پیش‌نمایش پیش‌نویس',
  noCurrent: 'هنوز نسخه‌ای منتشر نشده است.',
  textChanges: 'نمایش تغییرات متن',
  changeLegend: 'متن زیرخط‌دار افزوده شده و متن خط‌خورده حذف شده است.',
  largeComparison: 'تغییرات برای نمایش جزئیات زیاد است. هر دو سند بالا را بررسی کنید.',
  previewLoading: 'در حال بارگذاری پیش‌نمایش...',
  materialChange: 'تغییر اساسی است',
  previewChanged:
    'پیش‌نویس پس از پیش‌نمایش تغییر کرده است. این پیش‌نمایش را ببندید و پیش از انتشار دوباره بارگذاری کنید.',
  previewRequired: 'برای پیش‌نمایش معتبر انتشار، پیش‌نویس را دوباره بارگذاری کنید.',
  preserveSource:
    'این سند شامل جدول، تصویر یا HTML است. برای حفظ محتوا، متن اصلی را اینجا ویرایش کنید.',
  bold: 'پررنگ',
  italic: 'مورب',
  heading: 'عنوان',
  bullets: 'فهرست نشانه‌دار',
  numbers: 'فهرست شماره‌دار',
  quote: 'نقل قول',
  undo: 'واگرد',
  redo: 'از نو',
  formatting: 'قالب‌بندی',
  persian: 'محتوای فارسی',
  english: 'محتوای انگلیسی',
  editorLoading: 'در حال بارگذاری ویرایشگر...',
  requiredContent: 'محتوای فارسی و انگلیسی را وارد کنید.',
};
export const adminTosText = (locale: 'fa' | 'en') => (locale === 'fa' ? fa : en);
