/** Shared table copy. Callers supply translated column headers and cell content. */
export const dataTableLabels = {
  en: {
    loading: 'Loading...',
    empty: 'No results',
    selectAll: 'Select all rows',
    deselectAll: 'Deselect all rows',
    selectRow: (number: string) => `Select row ${number}`,
    expandRow: (name: string) => `Show details for ${name}`,
    collapseRow: (name: string) => `Hide details for ${name}`,
    details: 'Details',
    records: 'Records',
    rowCount: (number: string) => `${number} rows`,
    sortBy: 'Sort by',
    ascending: 'Ascending',
    descending: 'Descending',
    unsorted: 'Unsorted',
  },
  fa: {
    loading: 'در حال بارگذاری...',
    empty: 'نتیجه‌ای یافت نشد',
    selectAll: 'انتخاب همه ردیف‌ها',
    deselectAll: 'لغو انتخاب همه ردیف‌ها',
    selectRow: (number: string) => `انتخاب ردیف ${number}`,
    expandRow: (name: string) => `نمایش جزئیات ${name}`,
    collapseRow: (name: string) => `بستن جزئیات ${name}`,
    details: 'جزئیات',
    records: 'سوابق',
    rowCount: (number: string) => `${number} ردیف`,
    sortBy: 'مرتب‌سازی بر اساس',
    ascending: 'صعودی',
    descending: 'نزولی',
    unsorted: 'بدون ترتیب',
  },
} as const;
